import random

POSITIONS = [
    "director", "manager", "assistant", "analyst", "engineer", "designer",
    "developer", "coordinator", "specialist", "consultant", "supervisor",
    "administrator", "technician", "operator", "inspector", "architect",
    "strategist", "planner", "researcher", "scientist", "programmer",
    "tester", "writer", "editor", "artist", "photographer", "translator",
    "recruiter", "trainer", "auditor", "advisor", "commander",
    "lieutenant", "sergeant", "captain", "pilot", "navigator", "mechanic",
    "clerk", "officer", "associate", "executive", "lead", "senior", "junior",
    "chief", "head", "vice", "deputy", "principal", "staff", "intern",
    "agent", "operative", "handler", "guard", "broker", "trader", "vendor", 
    "courier", "messenger", "trainer", "magi",
    "watchman", "porter", "janitor", "custodian", "maintenance", 
    "fabricator", "assembler", "nurse", "doctor", "therapist", "counselor", 
    "teacher", "professor", "student", "scholar", "librarian", "archivist",
    "cook", "chef", "waiter", "barista", "server", "host", "receptionist",
    "ace", "aroma", "artist", "beauty", "biker", "bird", "blackbelt",
    "boarder", "bodybuilder", "bugcatcher", "burglar", "camper", "channeler",
    "collector", "cooltrainer", "crusher", "cyclist", "dancer",
    "delinquent", "diver", "dragontamer", "electrician", "expert", 
    "fisherman", "gambler", "gentleman", "guitarist", "harlequin", "hiker",
    "juggler", "kindler", "lady", "lass", "leader", "madame", "maid",
    "musician", "ninja", "oracle", "painter", "parasol", "picnicker", 
    "policeman", "preschooler", "psychic", "punk", "rancher", "rival", 
    "roughneck", "ruinmaniac", "sailor", "schoolkid", "skier", "striker",
    "swimmer", "tamer", "teammate", "triathlete", "tuber", "veteran",
    "waitress", "worker", "youngster", "elite", "champion", "hexmaniac",
    "advanced", "master", "novice", "skilled", "prime", "supreme", "ultimate", 
    "legendary", "mythic", "epic", "rare", "common", "basic", "standard", 
    "premium", "deluxe", "special", "unique", "custom", "tactical", "strategic", 
    "covert", "stealth", "shadow", "ghost", "phantom", "void", "cyber", "digital", 
    "quantum", "nuclear", "atomic", "stellar", "cosmic", "solar", "lunar", "astral", 
    "ethereal", "spectral", "temporal", "dimensional", "spatial", "crimson", "azure", 
    "golden", "silver", "platinum", "diamond", "crystal", "obsidian", "emerald", 
    "ruby", "sapphire", "onyx", "amber", "jade", "pearl", "opal", "swift", "rapid", 
    "quick", "fast", "slow", "steady", "calm", "fierce", "wild", "tame", "gentle", 
    "harsh", "soft", "hard", "light", "dark", "bright", "dim", "loud", "quiet", 
    "hot", "cold", "warm", "cool", "fresh", "stale", "new", "old", "young", 
    "ancient", "modern", "classic", "bold", "shy", "brave", "timid", "strong", 
    "weak", "tough", "fragile", "smart", "wise", "clever", "dull", "sharp", 
    "blunt", "smooth", "rough", "heavy", "big", "small", "huge", "tiny", "giant", 
    "mini", "long", "short", "tall", "wide", "narrow", "thick", "thin", "deep", 
    "shallow", "high", "low", "up", "down", "left", "right", "center", "inner", 
    "outer", "hidden", "visible", "secret", "open", "closed", "locked", "free", 
    "bound", "loose", "tight", "slack", "tense", "relaxed", "stressed", "active", 
    "passive", "dynamic", "static", "mobile", "fixed", "fluid", "solid", "rickety", 
    "jetstream", "bizarre"
]

NAMES = [
    "shinji", "rei", "asuka", "misato", "ikari", "kaworu", "balthasar", "caspar", 
    "melchior", 
    "goku", "vegeta", "gohan", "piccolo", "frieza", 
    "pascal", "turing", "ampere", "lovelace", "hopper", 
    "simon", "kamina", "yoko", "nia", "viral", 
    "jonathan", "jotaro", "dio", "joseph", "josuke", "giorno", "jolyne", "johnny", 
    "gappy", "jodio",
    "john", "winston", "charon", "sofia", "caine", 
    "okabe", "kurisu", "mayuri", "daru", "suzuha", "christina", 
    "ash", "misty", "brock", "may", "dawn", "serena", "clemont", "bonnie", "cilan", 
    "iris", "tracey", "max", "lana", "kiawe", "lillie", "sophocles", "mallow", "goh", 
    "chloe", "gary", "paul", "drew", "kenny", "zoey", "trip", "bianca", "stephan", 
    "cameron", "virgil", "tierno", "trevor", "shauna", "sawyer", "alain", "mairin", 
    "gladion", "hau", "acerola", "professor", "oak", "elm", "birch", "rowan", "juniper", 
    "sycamore", "kukui", "burnet", "cerise", "magnolia", "sonia", "jacq", "nemona", 
    "jessie", "james", "meowth", "giovanni", "archer", "ariana", "petrel", "proton", 
    "silver", "lance", "karen", "will", "koga", "bruno", "lorelei", "agatha", "sidney", 
    "phoebe", "glacia", "drake", "aaron", "bertha", "flannery", "lucian", "cynthia", 
    "alder", "diantha", "leon",
    "nico", "andy", "victor", "juiz", "top", "shen", "feng", "mui", "steven", "fuuko", 
    "barry", "ethan", "bocchi", "kikuri", "seika", 
    "loid", "yor", "anya", "handler", "fiona", "franky",
    "denji", "aki", "power", "makima", "reze", "quanxi", "kobeni", "himeno", "kishibe", 
    "yoshida", "chihiro", "shiba", "hakuri", "samura", 
    "dennis", "frank", "dee", "mac", "cricket", "sam", 
    "alan", "ellie", "ian", "lex", "tim", "ray", "henry", "martin", "sarah", 
    "roland", "peter", "nick", "kelly", "eddie", "dieter", "carter", "robert", "amanda", 
    "billy", "udesky", "cooper", "nash", "mark",
    "bruce", "clark", "diana", "barry", "arthur", "hal", "oliver", "dinah", "kara", 
    "barbara", "dick", "jason", "damian", "stephanie", "cassandra", "kate", "helena", 
    "selina", "pamela", "harvey", "edward", "oswald", "jarvis", "roman", "floyd", 
    "harley", "joker", "lex", "doomsday", "darkseid", "brainiac", "sinestro", "atrocitus", 
    "larfleeze", "saint", "zatanna", "raven", "starfire", "cyborg", "beast", "terra", 
    "blue", "booster", "ted",
    "peter", "tony", "steve", "natasha", "clint", "thor", "loki", "scott", "hope", 
    "wanda", "vision", "james", "bucky", "rhodey", "pepper", "happy", "may", "ned", 
    "michelle", "flash", "gwen", "miles", "miguel", "logan", "ororo", "kurt", "kitty", 
    "bobby", "warren", "jean", "erik", "charles", "remy", "anna", "betsy", "emma", 
    "hank", "reed", "sue", "ben", "franklin", "valeria", "stephen", "wong", "ancient", 
    "mordo", "carol", "monica", "kamala", "matt", "jessica", "luke", "danny", "wade", 
    "cable", "domino", "colossus", "deadpool", "gambit", "rogue", "storm", "wolverine", 
    "cyclops", "phoenix",
    "eren", "mikasa", "armin", "levi", "erwin", "hange", "sasha", "connie", "jean", 
    "marco", "annie", "reiner", "bertholdt", "ymir", "historia", "christa", "zeke", 
    "grisha", "carla", "keith", "shadis", "pixis", "nile", "dok", "rico", "mitabi", 
    "thomas", "mina", "samuel", "daz", "marlowe", "hitch", "boris", "gordon", "sandra", 
    "mylius", "jurgen", "ivan", "petra", "oluo", "eld", "gunther", "moblit", "nanaba", 
    "gelgar", "lynne", "henning", "tomas", "klaus", "marlene", "lauda", "franz", 
    "hannah", "gustav", "anka", "hugo", "rashad", 
    "aphrodite", "artemis", "zeus", "poseidon", "hades", "hera", "hephaestus", "ares", 
    "hermes", "dionysus", "hestia", "apollo", "athena", "demeter", "zagreus", "megaera", 
    "sisyphus", 
    "mipha", "revali", "daruk", "urbosa", "link", "zelda", "sidon"
]

def generate_name():
    """Generate a random worker name in the format 'position-name'"""
    position = random.choice(POSITIONS)
    name = random.choice(NAMES)
    return f"{position}-{name}"

