name: Test Store and Inference

on:
  pull_request:
    branches:
      - main
    paths:
      - 'sllm/serve/**'
      - 'sllm/cli/**'
      - 'tests/inference_test/**'
      - 'entrypoint.sh'

jobs:
  inference_store_tests:
    runs-on: self-hosted
    if: contains(github.event.pull_request.labels.*.name, 'ready-for-gpu-testing')
    container:
      image: pytorch/pytorch:2.3.0-cuda12.1-cudnn8-devel
      options: --gpus all
    defaults:
      run:
          shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies and create models directory
        run: |
          apt-get update
          apt-get install -y patch git npm wget

          echo "Creating models directory..."
          mkdir -p models
          echo "Models directory created at $(pwd)/models"
          echo "MODEL_FOLDER=$(pwd)/models" >> $GITHUB_ENV

      - name: Setup worker env
        shell: bash -l {0}
        run: |
          conda create -n sllm-worker python=3.10 -y

      - name: Import Python libraries (HEAD)
        run: |
          pip install -e .
          cd sllm_store && rm -rf build
          pip install .
          cd ..

      - name: Setup Environment and Start Services
        env:
          MODE: "HEAD"
        run: |
          chmod +x entrypoint.sh
          ./entrypoint.sh &
          sleep 10

      - name: Start Worker
        env:
          MODE: "WORKER"
          WORKER_ID: "1"
          RAY_HEAD_ADDRESS: "localhost:6379"
        run: |
          conda activate sllm-worker
          pip install -e ".[worker]"
          cd sllm_store && rm -rf build
          cd .. 
          chmod +x entrypoint.sh
          ./entrypoint.sh &
          sleep 10

      - name: Test sllm store
        run: |
          cd ./tests/inference_test
          python store_test.py

      - name: Test sllm inference
        if: always()
        run: |
          cd ./tests/inference_test
          python inference_test.py

      - name: Check results
        if: always()
        run: |
          if [ -f failed_models.json ]; then
            echo "::error::Tests failed - see above for details"
            exit 1
          fi
