name: Test Store and Inference

on:
  pull_request:
    branches:
      - main
    paths:
      - 'sllm/serve/**'
      - 'sllm/cli/**'
      - 'tests/inference_test/**'
      - 'entrypoint.sh'

jobs:
  inference_store_tests:
    runs-on: self-hosted
    if: contains(github.event.pull_request.labels.*.name, 'ready-for-gpu-testing')
    container:
      image: pytorch/pytorch:2.3.0-cuda12.1-cudnn8-devel
      options: --gpus all
    defaults:
      run:
          shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies and create models directory
        run: |
          apt-get update
          apt-get install -y patch git npm wget

          echo "Creating models directory..."
          mkdir -p models
          echo "Models directory created at $(pwd)/models"
          echo "MODEL_FOLDER=$(pwd)/models" >> $GITHUB_ENV

      - name: Setup head env
        shell: bash -l {0}
        run: |
          conda create -n sllm python=3.10 -y
          conda init bash

      - name: Setup worker env
        shell: bash -l {0}
        run: |
          conda create -n sllm-worker python=3.10 -y
          conda init bash

      - name: Start Head
        env:
          MODE: "HEAD"
        run: |
          source /opt/conda/etc/profile.d/conda.sh
          conda activate sllm
          pip install -e .
          cd sllm_store && rm -rf build
          pip install .
          cd ..
          chmod +x entrypoint.sh
          ./entrypoint.sh &
          sleep 10

      - name: Start Worker
        env:
          MODE: "WORKER"
          WORKER_ID: "0"
          STORAGE_PATH: $MODEL_FOLDER
          RAY_HEAD_ADDRESS: "localhost:6379"
        run: |
          source /opt/conda/etc/profile.d/conda.sh
          conda activate sllm-worker
          pip install -e ".[worker]"
          cd sllm_store && rm -rf build
          cd ..
          chmod +x entrypoint.sh
          ./entrypoint.sh &
          sleep 10

      - name: Serve Worker
        env:
          CUDA_VISIBLE_DEVICES: "0"
        run: |
          source /opt/conda/etc/profile.d/conda.sh
          conda activate sllm-worker
          sllm-store-server & 
          sleep 10

      - name: Serve Head
        run: |
          source /opt/conda/etc/profile.d/conda.sh
          conda activate sllm
          sllm-serve start &
          sleep 10

      - name: Test sllm store
        run: |

          source /opt/conda/etc/profile.d/conda.sh
          conda activate sllm
          cd ./tests/inference_test
          python store_test.py
          python inference_test.py

      - name: Check results
        if: always()
        run: |
          if [ -f failed_models.json ]; then
            echo "::error::Tests failed - see above for details"
            exit 1
          fi
