Name: Test Store and Inference 

on: 
  pull_request: 
    branches:
      - main
    paths:
      - 'sllm/serve/**'
      - 'sllm/cli/**'
      - 'tests/inference_test/**'
      - 'docker-build.sh'

jobs: 
  inference_store_tests:
    runs-on: self-hosted
    if: contains(github.event.pull_request.labels.*.name, 'ready-for-gpu-testing')
    container:
      image: pytorch/pytorch:2.3.0-cuda12.1-cudnn8-devel
      options: --gpus all
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment and Start Services
        run: |
          chmod +x entrypoint.sh
          ./entrypoint.sh
      
      - name: Initialize conda and paths
        run: |
          echo "Activating conda environment..."
          source ~/miniconda3/bin/activate
          conda activate sllm
          
          echo "Creating models directory..."
          mkdir -p models
          echo "Models directory created at $(pwd)/models"
          
          echo "Setting up environment variables..."
          export MODEL_FOLDER=$(pwd)/models
          export LLM_SERVER_URL=http://127.0.0.1:8343/
          echo "MODEL_FOLDER is set to: $MODEL_FOLDER"
          echo "LLM_SERVER_URL is set to: $LLM_SERVER_URL"

      - name: Test sllm-cli deploy
        run: |
          source ./tests/inference_test/inference_conda.sh
          python ./tests/inference_test/store_test.py
    
      - name: Test inference
        if: always()
        run: |
          source ./tests/inference_test/inference_conda.sh
          python ./tests/inference_test/inference_test.py

      - name: Check results 
        if: always()
        run: |
          if [ -f failed_models.json ]; then
            echo "::error::Tests failed - see above for details"
            exit 1
          fi
