name: Test Store and Inference

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, labeled]
    paths:
      - 'tests/inference_test/**'
      - 'sllm_store/**'

jobs:
  inference_store_tests:
    runs-on: [self-hosted, nvidia]
    if: contains(github.event.pull_request.labels.*.name, 'ready-for-gpu-testing')
    timeout-minutes: 90
    container:
      image: nvcr.io/nvidia/cuda:12.6.1-cudnn-devel-ubuntu22.04
      options: --gpus all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y ca-certificates git
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
          pip install --no-cache-dir --upgrade certifi
          echo "SSL_CERT_FILE=$(python -m certifi)" >> "$GITHUB_ENV"

      # Python Tests
      - name: Install ServerlessLLM
        run: |
          cd sllm_store && pip install .

      - name: Start sllm-store Server
        run: |
          export MODEL_FOLDER="./models"
          mkdir -p $MODEL_FOLDER
          nohup sllm-store start --storage-path $MODEL_FOLDER --mem-pool-size 16GB > server.log 2>&1 &
          sleep 10

      - name: Test models
        timeout-minutes: 60
        run: |
          export MODEL_FOLDER="./models"
          pytest -s tests/inference_test/store_test.py
          pytest -s tests/inference_test/inference_test.py

      - name: Check results
        if: always()
        run: |
          cd tests/inference_test
          if [ -f failed_models.json ]; then
            echo "::error::Tests failed - see above for details"
            exit 1
          fi
