name: Formatting

on:
  workflow_dispatch:
  pull_request:
    branches:
      '**'
  merge_group:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # formatting and basic install on cpu-only machine
  unit-tests:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: environment
        run: |
          which python
          python --version

      - name: Install dependencies
        run: |
          # Previously we would do pip install .[dev] but this is causing out of
          # space errors start with torch 2.1.0 release
          pip install -r requirements-lint.txt

      - name: Formatting checks
        run: |
          pip show pre-commit clang-format
          pre-commit run --all-files
