name: ROCm test

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main
    paths:
      - 'sllm_store/**'


jobs:
  rocm_test:
    runs-on: [self-hosted, amd]
    if: contains(github.event.pull_request.labels.*.name, 'ready-for-gpu-testing')
    container:
      image: rocm/vllm-dev:base_ROCm-6.3.1_20250528_tuned_20250530
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
            apt-get update && apt-get install -y ca-certificates git wget bzip2
            python -m pip install --upgrade pip
            pip install -r requirements-test.txt

      - name: Set up using existing torch
        working-directory: sllm_store
        run: |
            python using_existing_torch.py

      - name: Build wheel
        working-directory: sllm_store
        shell: bash
        env:
          PYTORCH_ROCM_ARCH: "gfx906 gfx908 gfx90a gfx940 gfx941 gfx942 gfx1030 gfx1100"
        run: |
            export PATH=$PATH:/opt/rocm/bin:/libtorch/bin
            export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rocm/lib/:/libtorch/lib
            pip install -r requirements-build.txt
            python setup.py sdist bdist_wheel

      - name: Install wheel
        working-directory: sllm_store
        run: |
            pip install dist/*.whl

      - name: Run Python tests (excluding vllm)
        working-directory: sllm_store
        run: |
            pytest tests/python/test_save_model.py
            pytest tests/python/test_utils.py

      - name: Run C++ tests
        working-directory: sllm_store
        env:
          PYTORCH_ROCM_ARCH: "gfx906 gfx908 gfx90a gfx940 gfx941 gfx942 gfx1030 gfx1100"
        run: |
            export PATH=$PATH:/opt/rocm/bin:/libtorch/bin
            export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rocm/lib/:/libtorch/lib
            bash cpp_build.sh
            ctest --output-on-failure
