name: Sllm Store Python Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: Install CUDA 12.1
        run: |
          bash -x .github/workflows/scripts/cuda-install.sh 12.1 ubuntu-22.04

      - name: Install ServerlessLLM
        run: |
          cd serverless_llm/store && pip install .

      - name: Run tests
        run: |
          pytest serverless_llm/store/tests/python
